--application =
--{
--    content =
--    {
--        width = 640,
--        height = 960,
--        scale = "letterbox",
--        --        width = 320,
--        --        height = 480,
--        --        scale = "zoomEven",
--        fps = 60,
--        antialias = false,
--        xalign = "center",
--        yalign = "center",
--
--        imageSuffix =
--        {
--            ["@2x"] = 2
--        }
--
--    }
--}