require("refPointConversions")
display.setStatusBar( display.HiddenStatusBar )
local storyboard = require "storyboard"

local model = system.getInfo("model")
--print(model)
-- load menu screen
--local testMemo = require ("testMemoryleck")
--testMemo.new()
--storyboard.gotoScene( "Firstpage")
--storyboard.gotoScene( "test")
--storyboard.gotoScene( "discharge_main")
--storyboard.gotoScene( "game-scene")
--storyboard.gotoScene( "puzzle")
--storyboard.gotoScene( "puzzleCode")
--storyboard.gotoScene( "codePem")
--storyboard.gotoScene( "mission_clear")
--storyboard.gotoScene( "title_page")
--storyboard.gotoScene( "map")
--storyboard.gotoScene( "map_substate")
--storyboard.gotoScene( "chapter_select")
--storyboard.gotoScene( "misstion")
--storyboard.gotoScene( "ticket_shop")
--storyboard.gotoScene( "characterAll")

--storyboard.gotoScene( "team_item")
--storyboard.gotoScene( "unit_box")
--storyboard.gotoScene( "unit_main")
--storyboard.gotoScene( "pageWith")
storyboard.gotoScene( "title_page")
--storyboard.gotoScene( "menu_barLight")
--storyboard.gotoScene( "mission_clear")
--storyboard.gotoScene( "map")
--storyboard.gotoScene( "characterAll")
--storyboard.gotoScene( "guest")
--storyboard.gotoScene( "team_main")
--storyboard.gotoScene( "item_setting")
--storyboard.gotoScene( "team_select")
--storyboard.gotoScene( "team_main")
--storyboard.gotoScene( "commu_main")
--storyboard.gotoScene( "friend_list")
--storyboard.gotoScene( "character")

--storyboard.gotoScene( "request_list")
--storyboard.gotoScene( "shop_money")
--storyboard.gotoScene( "gacha")
--storyboard.gotoScene( "gacha_card")
--storyboard.gotoScene( "upgrade_main")
--storyboard.gotoScene( "power_up_main")
--storyboard.gotoScene( "battle_item")
--storyboard.gotoScene( "sell_item")
--storyboard.gotoScene( "team_select")
--storyboard.gotoScene( "shop_main")
--storyboard.gotoScene( "mission_clear")
--storyboard.gotoScene( "misstion")
--storyboard.gotoScene( "characterprofile")
--storyboard.gotoScene( "character_show")
--storyboard.gotoScene( "player_list")
--storyboard.gotoScene( "headTitle")
--storyboard.gotoScene( "menu_barLight")
--storyboard.gotoScene( "databaseConnect")
--storyboard.gotoScene( "team_item")
--storyboard.gotoScene( "includeFunction")
--storyboard.gotoScene( "discharge_main")
--storyboard.gotoScene( "characterAll")



